version: '3.9'

services:
  php-env:
    build: .
    ports:
      - "9000:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql_db
  mysql_db:
    image: mysql:latest
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: users
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./src/init.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - "9906:3306"
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - "9001:80"
    environment:
      - PMA_ARBITRARY=1

